# Generated by Django 2.2.6 on 2019-10-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('shifts', '0003_auto_20191013_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_shift', models.DateField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.ExamTypes')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Location')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Room')),
                ('shift_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.ShiftTime')),
            ],
        ),
    ]
