# Generated by Django 2.2.6 on 2019-10-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='location',
        ),
    ]
