# Generated by Django 2.2.6 on 2019-12-14 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0007_auto_20191102_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtypes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
