# Generated by Django 2.2.6 on 2019-12-14 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_examtypes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtypes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ExamTypes', to=settings.AUTH_USER_MODEL),
        ),
    ]
