# Generated by Django 2.2.6 on 2019-12-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_shifttime_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shifts',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modality', to='shifts.Modality'),
        ),
    ]
