# Generated by Django 2.2.6 on 2019-12-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_auto_20191221_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtypes',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modality_exams', to='shifts.Modality'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modality_shifts', to='shifts.Modality'),
        ),
    ]
