# Generated by Django 2.2.6 on 2019-12-22 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0012_auto_20191222_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='coordinator',
            field=models.ManyToManyField(null=True, related_name='modalities', to=settings.AUTH_USER_MODEL),
        ),
    ]
