# Generated by Django 2.2.6 on 2019-12-22 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_modality_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='coordinator',
            field=models.ManyToManyField(related_name='modalities', to=settings.AUTH_USER_MODEL),
        ),
    ]
