# Generated by Django 2.2.6 on 2019-12-19 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0002_auto_20191217_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=20, unique=True)),
                ('coordinator', models.ForeignKey(limit_choices_to={'groups_name': 'Coordinator'}, on_delete=django.db.models.deletion.PROTECT, related_name='Modality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
