# Generated by Django 2.2.6 on 2019-12-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_modality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modality',
        ),
    ]
