//TECHNOLOGISTS
export const GET_TECHS = "GET_TECHS";
export const DELETE_TECH = "DELETE_TECH";
export const ADD_TECH = "ADD_TECH";

//ERRORS AND MESSAGES
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//EXAM TYPES
export const GET_EXAMTYPES = "GET_EXAMTYPES";
export const ADD_EXAMTYPE = "ADD_EXAMTYPE";

//SHIFT TIMES
export const GET_SHIFTTIMES = "GET_SHIFTTIMES";
export const BUILD_SHIFTTIMES = "BUILD_SHIFTTIMES";
export const DELETE_SHIFTTIME = "DELETE_SHIFTTIME";

//RESOURCES
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_ROOMS = "GET_ROOMS";

//ASSIGNMENT OF SHIFTS
export const SHIFT_ADDED = "SHIFT_ADDED";
export const SHIFT_RETRIEVE = "SHIFT_RETRIEVE";

//MISC
export const DUPLICATE_ITEMS = "DUPLICATE ITEMS";
export const OVERRIDE_ITEMS = "OVERRIDE ITEMS";
